# Generated by Django 2.1.5 on 2019-02-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
    ]
