# Generated by Django 2.1.5 on 2019-02-07 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0002_auto_20190207_2151'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together={('ref',)},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('bar', 'reference')},
        ),
    ]
