# Generated by Django 2.1.5 on 2019-01-28 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0004_auto_20190127_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='bars.Bar'),
        ),
    ]
