# Generated by Django 2.1.5 on 2019-01-28 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0005_auto_20190128_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bars.Bar'),
        ),
    ]
